# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DDC_cpp <- function(X, tolProbCell, tolProbRow, tolProbReg, tolProbCorr, corrlim, combinRule, rowdetect, includeSelf, fastDDC, absCorr, qdim, transFun, treetype, searchtype, radius, eps, bruteForce, k, numiter, precScale) {
    .Call(`_cellWise_DDC_cpp`, X, tolProbCell, tolProbRow, tolProbReg, tolProbCorr, corrlim, combinRule, rowdetect, includeSelf, fastDDC, absCorr, qdim, transFun, treetype, searchtype, radius, eps, bruteForce, k, numiter, precScale)
}

Wrap_cpp <- function(X, loc, scale, precScale) {
    .Call(`_cellWise_Wrap_cpp`, X, loc, scale, precScale)
}

estLocScale_cpp <- function(X, type, precScale) {
    .Call(`_cellWise_estLocScale_cpp`, X, type, precScale)
}

