# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DDC_cpp <- function(X, tolProbCell, tolProbRow, tolProbReg, tolProbCorr, corrlim, combinRule, includeSelf, fastDDC, qdim, transFun, k, numiter, precScale, standType, corrType, nCorr, nLocScale, goodCols) {
    .Call(`_cellWise_DDC_cpp`, X, tolProbCell, tolProbRow, tolProbReg, tolProbCorr, corrlim, combinRule, includeSelf, fastDDC, qdim, transFun, k, numiter, precScale, standType, corrType, nCorr, nLocScale, goodCols)
}

Wrap_cpp <- function(X, loc, scale, precScale) {
    .Call(`_cellWise_Wrap_cpp`, X, loc, scale, precScale)
}

estLocScale_cpp <- function(X, nLocScale, type, precScale, center, alpha) {
    .Call(`_cellWise_estLocScale_cpp`, X, nLocScale, type, precScale, center, alpha)
}

unimcd_cpp <- function(y, alpha) {
    .Call(`_cellWise_unimcd_cpp`, y, alpha)
}

findCellPath_cpp <- function(predictors, response, weights, Sigmai, naMask) {
    .Call(`_cellWise_findCellPath_cpp`, predictors, response, weights, Sigmai, naMask)
}

allpreds_cpp <- function(X, S, mu, W) {
    .Call(`_cellWise_allpreds_cpp`, X, S, mu, W)
}

Objective_cpp <- function(X, W, mu, Sigma, Sigmai) {
    .Call(`_cellWise_Objective_cpp`, X, W, mu, Sigma, Sigmai)
}

updateW_cpp <- function(X, W, mu, Sigma, Sigmai, lambda, h) {
    .Call(`_cellWise_updateW_cpp`, X, W, mu, Sigma, Sigmai, lambda, h)
}

